# Generated by Django 4.1.6 on 2023-02-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_fullsolution_managers_instalaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('contrato', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.reporte')),
            ],
        ),
    ]
