# Generated by Django 4.1.5 on 2023-01-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('report_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atrasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('servicio', models.CharField(max_length=100)),
                ('monto', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('distribuidor', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.reporte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
