# Generated by Django 4.1.6 on 2023-02-25 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fullsolution',
            managers=[
                ('audits', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.reporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cancelaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.reporte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
